package ca.magenta.tca.drools.rules.drl

import ca.magenta.tca.fact.category.Message;
import ca.magenta.tca.fact.MappedMsg;

rule "Message"
salience -999
    when
        message : Message(    )
    then
      System.out.println( "Got Message: [" + message.toString() + "]" );
      retract(message);
end

rule "AlloT"
salience 0
    when
        message: MappedMsg( getPayload().contains("allo")   )
    then
        System.out.println( "AlloT Matched: [" + message.toString() + "]" );
end


rule "Allo"
salience 0
    when
        mappedMsg : MappedMsg( payload.contains("allo"), payload : payload )
  then
      System.out.println( "Allo Matched: [" + payload + "]" );
end

rule "Bonjour"
salience 0
  when
      MappedMsg( payload.contains("bonjour"), payload : payload )
  then
      System.out.println( "Bonjour Matched: [" + payload + "]" );
end