package ca.magenta.tca.fact

import ca.magenta.tca.drools.service.TcaService;
import ca.magenta.tca.fact.category.Message;

declare Message
	@role( event )
end

declare MappedMsg
	@role( event )
end

rule "Message"
salience -999
    when
        message : Message(    )
    then
      TcaService.getLogger().info("Got Message: [{}]",message.toString());
end

rule "AlloT"
salience 0
    when
        message: MappedMsg( payloadContains("allo")   )
    then
        System.out.println( "AlloT Matched: [" + message.toString() + "]" );
      TcaService.getLogger().info("Got Message: [{}]",message.toString());
end


rule "Allo"
salience 0
    when
        mappedMsg : MappedMsg( payload.contains("allo"), payload : payload )
  then
      System.out.println( "Allo Matched: [" + payload + "]" );
end

rule "Bonjour"
salience 0
  when
      MappedMsg( payload.contains("bonjour"), payload : payload )
  then
      System.out.println( "Bonjour Matched: [" + payload + "]" );
end